openapi: 3.0.3
info:
  title: User Profile API — Language Preference Extension
  version: 0.2.0
  description: |
    Extension to the existing /api/users/profile endpoint to support
    preferred_language field for English/Urdu locale persistence.

paths:
  /api/users/profile:
    post:
      summary: Create or update user profile (upsert)
      description: |
        Existing endpoint — extended with preferred_language field.
        Creates profile if none exists, updates if already present.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileRequest'
            examples:
              set-urdu:
                summary: Set language to Urdu
                value:
                  preferred_language: "ur"
              full-profile:
                summary: Full profile with language
                value:
                  software_level: "intermediate"
                  hardware_level: "beginner"
                  topics: ["python", "ros2"]
                  preferred_language: "ur"
      responses:
        '200':
          description: Profile updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '401':
          description: Unauthorized — missing or invalid token
        '422':
          description: Validation error — invalid preferred_language value

    get:
      summary: Get current user's profile
      description: |
        Existing endpoint — response now includes preferred_language field.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Profile retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '401':
          description: Unauthorized
        '404':
          description: Profile not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserProfileRequest:
      type: object
      properties:
        software_level:
          type: string
          enum: [beginner, intermediate, advanced]
        hardware_level:
          type: string
          enum: [beginner, intermediate, advanced]
        topics:
          type: array
          items:
            type: string
        preferred_language:
          type: string
          enum: [en, ur]
          default: en
          description: User's preferred language for the textbook UI

    UserProfileResponse:
      type: object
      required:
        - id
        - supabase_user_id
        - preferred_language
        - created_at
        - updated_at
      properties:
        id:
          type: integer
        supabase_user_id:
          type: string
          format: uuid
        software_level:
          type: string
          nullable: true
        hardware_level:
          type: string
          nullable: true
        topics:
          type: array
          items:
            type: string
          nullable: true
        preferred_language:
          type: string
          enum: [en, ur]
          default: en
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
